
version: '3'
services:
  jp-sentence-generator:
    env_file:
      - .env
    container_name: jp-sentence-generator
    build:
      context: "."
    ports:
     - "8501"
    environment:
      OPENAI_API_KEY: ${OPENAI_API_KEY}
      OPENAI_USER: ${OPENAI_USER}
      FORVO_API_KEY: ${FORVO_API_KEY}